doctrine:
    dbal:
        # url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        driver: '%env(resolve:DRIVER)%'
        host: '%env(resolve:HOST)%'
        port: '%env(resolve:PORT)%'
        dbname: '%env(resolve:DBNAME)%'
        user: '%env(resolve:DBUSER)%'
        password: '%env(resolve:PASSWORD)%'
        charset: '%env(resolve:CHARSET)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:

            Auth:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Auth/Infrastructure/Repository/Mapping'
                prefix: 'App\Auth\Domain'
            Shop:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Shop/Infrastructure/Repository/Mapping'
                prefix: 'App\Shop\Domain'
            Visit:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Visit/Infrastructure/Repository/Mapping'
                prefix: 'App\Visit\Domain'
            Product:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Product/Infrastructure/Repository/Mapping'
                prefix: 'App\Product\Domain'


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
